### ISSUE TITLE
VOC algemeen - Status van dit document

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-wegenenverkeer#11]
Niet conform nieuwe situatie:
- verwijzing naar recente vocabularia op https://data.vlaanderen.be/ns is niet meer relevant;
- verwijzing naar werkgroep Datastandaarden OSLO is niet meer terecht;
- bevat nog ten onrechte link naar "publieke reviewdiscussielijst" = https://github.com/Informatievlaanderen/OSLO-Public-Discussion.

**Comment by deefbas** [comment]
Zou moeten in orde zijn volgens bespreking met Jordy.

**Comment by GeoniusInfra** [comment]
In versie 22 is deze aanpassing verwerkt.
