### ISSUE TITLE
VOC algemeen - klassen in meervoud

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-wegenenverkeer#12]
Vele klassen hebben een klassenaam en label in het meervoud. Schept verwarring --> klassenamen en labels enkelvoud maken

**Comment by deefbas** [comment]
Doorlopen, aangepast waar nodig en zou in orde moeten zijn.

**Comment by mvanbrab** [comment]
Tiens, toolchain heeft gerund en toch... Mogelijks is deze update niet doorgesijpeld tot bij jordy?
![afbeelding](https://user-images.githubusercontent.com/6448245/60035043-363cb400-96ac-11e9-9c3e-69f464917885.png)

**Comment by deefbas** [comment]
Is in orde denk ik 
![image](https://user-images.githubusercontent.com/52077150/60107771-c0961e00-9767-11e9-8953-0fc4d4c1cce4.png)

**Comment by mvanbrab** [comment]
Enkele zijn allicht nog aan de aandacht ontsnapt.

In het vocabularium onderdeel zie ik nog:

"Andere ecologische maatregelen" (uri is ok, label niet)
"Geprefabriceerde betonelementen" (uri is ok, label niet)
"Wv bevs toestellen" (uri is ok, label niet; uri bevat "WvBevsToestelMethode")

**Comment by deefbas** [comment]
Deze zijn reeds aangepast in EA maar nog niet door de publicatie gekomen.

Bv :

[cid:image001.png@01D52DA2.B5108BD0]

**Comment by deefbas** [comment]
Ok, rechtstreeks reply-en via email geeft nogal wat junk mee :-).

Degene die je doorgaf zijn paar dagen geleden aangepast : 
![image](https://user-images.githubusercontent.com/52077150/60332254-b6a63200-9996-11e9-9d75-6e6ab73dbe31.png)

Maar eerlijkheid biedt me te bekennen dat Andere Ecologische Maatregelen idd door de mazen van het net was geslipt :-)....ook aangepast nu.

Bedankt voor je opmerking!

Mvg 
Davy
