### ISSUE TITLE
VOC algemeen - labels van eigenschappen

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-wegenenverkeer#13]
Alle labels van eigenschappen beginnen met hoofdletter --> wijzigen in kleine letter

**Comment by GeoniusInfra** [comment]
Is aangepast

**Comment by GeoniusInfra** [comment]
Is aangepast

**Comment by mvanbrab** [comment]
Na aanpassing beginnen alle labels van klassen nu ook met een kleine letter --> wijzigen in hoofdletter...
en zien dat de aanpassing voor labels (naar kleine letter) blijft.

**Comment by deefbas** [comment]
Bug in script, opgelost en terug laten draaien en zou de klassen issue moeten oplossen na herpublicatie.

**Comment by mvanbrab** [comment]
Is grotendeels in orde, maar blijkbaar nog niet overal.

Tegenvoorbeelden (niet limitatief)
in abstracten: BOK-afwaarts (bok opwaarts is wel goed...)
in onderdeel: TrottoirBandvorm, VHAG code

**Comment by deefbas** [comment]
Hmmm, raar, ik denk dat alle aanpassingen nog niet zijn gepubliceerd. Net gecontroleerd in EA en lijkt me in orde :

![image](https://user-images.githubusercontent.com/52077150/60080551-6fb70300-9730-11e9-8fc5-b25c44abbed6.png)

**Comment by deefbas** [comment]
TrottoirBandvorm is ondertussen ook uitgeklaard van waar dit kwam en aangepast. Bij volgende publicatie van het VOC zouden deze problemen moeten weg zijn.

**Comment by mvanbrab** [comment]
Is OK nu.
