### ISSUE TITLE
VOC algemeen - herhaling van de term vooraan de definitie

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-wegenenverkeer#18]
Begin een definitie niet met het herhalen van de term naam, bijvoorbeeld (eigenschap boomspiegel in VOC abstracten: "De boomspiegel is het stuk grond rondom de stam van een boom, en in de ideale situatie minstens zo groot is als de kruin van de boom."

**Comment by deefbas** [comment]
Heb een script laten draaien om deze gevallen op te sporen. Aangepast waar deze ontdekt werden.
