### ISSUE TITLE
suggestie versionering

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLOthema-wegenenverkeer#2]
Misschien kan je voor de versionering van de implementatiemodellen 
de urls 
{domein}/doc/implementatiemodel/awv-object/ontwerpdocument/{versie}

gebruiken.

Dan staat dat ook niet in de titel alleen.

**Comment by bertvannuffelen** [comment]
Er zijn nog wel wat deadlinks die het gevolg zijn van het niet volledig configureren van de publicatiepunten. 
Als je een vocabularium op /ns als path zet dan moet je die ook configureren zie onderstaand voorbeeld.


```[
   {
    "urlref": "/doc/vocabularium/wegenenverkeer/implementatieelement/ontwerpdocument/niet-bepaald",
    "repository": "https://github.com/Informatievlaanderen/OSLOthema-wegenenverkeer",
    "branchtag": "master",
    "name": "wegenenverkeer-implementatieelement",
    "navigation": {
      "previous": "/doc/vocabularium/wegenenverkeer/implementatieelement/ontwerpdocument/niet-bepaald"
    }
  },
  {
    "urlref": "/ns/implementatieelement",
    "seealso": "/doc/vocabularium/wegenenverkeer/implementatieelement/ontwerpdocument/niet-bepaald/",
    "type": "voc"
  },
```

Zoals in de issue al aangehaald zou ik correcte versionering gaan toepassen en dus nu niet-bepaald vervangen door vxx volgens een schema dat jullie willen volgen.
Elke keer kan dan ook de previous en next aanpassen. En op deze manier gebruikers de juiste informatie weergeven. Je kan dan een issue hebben op v18 en opgelost in v20. En dan is dat duidelijk.
De versieloze publicatiepunten verwijzen naar de laatste versie.

Dit is inderdaad wel wat manueel configuratie werk, maar het zal jullie communicatie over de wijzigingen heel wat gemakkelijker maken.

Ik zou dan ook de URLs in de homepagina aanpassen naar de versieloze varianten.

mvg,

Bert

**Comment by GeoniusInfra** [comment]
is aangepast
