### ISSUE TITLE
VOC abstracten - klasse Proef a posteriori voor de kantopsluiting., label

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-wegenenverkeer#26]
Label wijkt ver af van klassenaam GestandaardiseerdeKantopsluiting.
Label bevat een punt aan het einde

**Comment by deefbas** [comment]
Stond een dubbel label-nl bij deze klasse. Foutieve label-nl verwijderd.

**Comment by deefbas** [comment]
En punt weggehaald bij label-nl van de Proef a posteriori klasse
