### ISSUE TITLE
VOC abstracten - klasse V r i draag constructies, label

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-wegenenverkeer#28]
Onduidelijk label; wat is V r i?

**Comment by deefbas** [comment]
VRI = verkeersregelinstallatie...dus best voluit schrijven?

**Comment by mvanbrab** [comment]
Is veel duidelijker voor niet-ingewijden.

**Comment by deefbas** [comment]
Aangepast, voor volgende pub
