### ISSUE TITLE
VOC algemeen - geen CamelCase in labels

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-wegenenverkeer#37]
geen CamelCase in labels maar correct Nederlands
Slechte voorbeelden uit VOC onderdeel:
WindreflectorDrager
ZonnepaneelMerk
ZonnepaneelType

**Comment by deefbas** [comment]
Undo of CamelCase heeft gelopen en zou volgende pub moeten in orde zijn.
