### ISSUE TITLE
VOC algemeen - lege definities

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-wegenenverkeer#38]
Er moet overal een definitie staan.
Ontbreekt bijvoorbeeld in VOC onderdeel voor:
BevestigingsbeugelType

Idem voor label.
Ontbreekt bijvoorbeeld in VOC installatie voor:
Riolering

**Comment by mvanbrab** [comment]
Een overzicht van alle missende definities per vocabularium kan je maken met een search op  `Missing "definition-nl"` in het report zoals gesteld in #6.

**Comment by deefbas** [comment]
Aangepast. Er zouden geen lege definities meer mogen voorkomen na pub.
