### ISSUE TITLE
dubbele entries

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLOthema-wegenenverkeer#4]
https://data.vlaanderen.be/ns/wegenenverkeer/onderdeel#VoegType komt 2x voor in vocabularium onderdeel.

Dat leidt tot inconsistenties.

**Comment by mvanbrab** [comment]
Idem voor https://data.vlaanderen.be/ns/wegenenverkeer/onderdeel#WvBevsToestellen. Oorzaak is dubbel voor komen van de classifier "WvBevsToestellen" in het model (een keer al enumeratie, een keer als datatype), met twee verschillende labels. Zie ook #36 .

**Comment by deefbas** [comment]
-1 van de 2 voegtypes uniek gemaakt (TunnelVoegType ipv VoegType).
-Het datatype noemt nu WvBevsToestelMethode aangezien dit een Union datatype (als keuzelijst) fungeert om de methode aan te duiden.
