### ISSUE TITLE
VOC implementatieelement - initiële waarde op verkeerde manier ingegeven in KwantWrdInMeter en alle gelijkaardige

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-wegenenverkeer#43]
In deze klassen werd de initiële waarde van het attribuut als volgt ingegeven:
![afbeelding](https://user-images.githubusercontent.com/6448245/60095458-e2cf7200-974e-11e9-9d72-42d7ee991eaa.png)

Dit is fout. Correcte manier:
![afbeelding](https://user-images.githubusercontent.com/6448245/60095175-44dba780-974e-11e9-9441-07e7df4dfd44.png)

(zie ook mail van @GeertThijs "opgelegde eenheden" van 21/5/2019: "Hoe je dit precies doet is beschreven in bijgaande nota")

**Comment by deefbas** [comment]
Aangepast en zou ok moeten zijn.

**Comment by deefbas** [comment]
De waarde van de initial value bij de kwantitatieve waarden, die het formaat en de begrenzing van deze waarde verduidelijkt, is nergens zichtbaar op de pagina :

https://wegenenverkeer-test.data.vlaanderen.be/doc/implementatiemodel/eenvoudige-datatypes/

**Comment by mvanbrab** [comment]
@deefbas: Ik stel voor dat je je operaties op deze issue van 3 dagen geleden (heropenen, labels, assignment) ongedaan maakt en voor het overzicht een nieuw issue aanmaakt. De fout die ik aanhaalde is immers door jou opgelost en het nieuwe probleem dat je aanhaalt is een nieuw verhaal. Verwijs indien nodig naar deze issue met het matje...

**Comment by deefbas** [comment]
Done, zal nieuwe issue loggen voor het probleem.
