### ISSUE TITLE
deze versie verwijst naar data.vlaanderen.be domein

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLOthema-wegenenverkeer#44]
De metadata "deze versie" verwijst altijd naar data.vlaanderen.be.
Dat zou domein configureerbaar moeten zijn.

**Comment by deefbas** [comment]
Dit is opgelost. Verijst nu naar wegenenverkeer.data.vlaanderen.be....

**Comment by bertvannuffelen** [comment]
OSLO-Specgenerator aangepast
