### ISSUE TITLE
IM algemeen - stereotypes <<OSLO-...>> in het diagram

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-wegenenverkeer#49]
Het is geen OSLO stijl om stereotypes `<<OSLO-Class>>`, `<<OSLO-Attribute>>` en andere te laten zien in het diagram.

**Comment by deefbas** [comment]
Diagrammen zijn aangepast. Volgende pub zou dit moeten in orde zijn.
