### ISSUE TITLE
VOC onderdeel - detaillijst suggesties benamingen labels, UML namen en daaruit uri's

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-wegenenverkeer#54]
Klasse **Anti-parkeerpaal**
(vergeleken met Klasse Antiparkeerpaal type)
(consequentie in naamgeving)
suggestie: label aanpassen naar "Antiparkeerpaal" (ook uri aanpassen)

Klasse **Bloemrijk grasland grasland - fase4**
Klasse **Soortenrijk schraal grasland grasland - fase5**
(consequentie in naamgeving - vergelijk met andere klassen met grasland in de naam)
suggestie: één keer grasland in labels en uri's

Klassen met "template" in het label maar niet in de uri en omgekeerd
Klasse **Copro markering template** - https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#CoproMarkering
Klasse **Dwarse markering type** - https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#DwarseMarkeringTypeTemplate
Klasse **Figuratie type** -  	https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#FiguratieTypeTemplate
(consequentie in naamgeving)
suggestie: overal template weglaten ofwel overal toevoegen, in labels en uri's

Klasse **Grond ophoging**
vergelijk met Klasse Grondafdekking
(consequentie in naamgeving)
suggestie: label aan elkaar schrijven

Klasse **Laagtype van de butimineuze verharding.**
suggestie: punt verwijderen uit label

Klasse **Overlangse markering datatype** - https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#OverlangsemarkeringType
Klasse **Overlangse markering type** - https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#OverlangseMarkeringType
(nauwelijks verschillende uri's: slechts case van  één karakter)
suggestie: eerste uri fragment aanpassen naar #Overlangse**M**arkering**Data**type

Klasse **Plankenbetuining**
Klasse **Plankenbetuining gerecycleerd**
Klasse **Plankenbetuining hout**
Klasse **Plankenbetuining materiaal**
(consequentie in uri fragmenten: #Plankenbetuining, #BetuiningGerecycleerd, #BetuiningHout, #PaalBetuiningMateriaal)
suggestie: alle uri's fragmenten beginnen met #Planken, geen met #Paal

Klasse **Sw.gehost op**
Klasse **Sw.onderdeel van**
suggestie: "Sw." vervangen door "Software "

Eigenschap **bijmengingshoofdnaam**
suggestie: "code" toevoegen aan label (zoals in z'n uri fragment #Grondbijmenging.bijmengingshoofdnaamcode)

**Comment by deefbas** [comment]
Bovenstaande issues zijn aangepast, volgende pub zou in orde moeten zijn.

**Comment by mvanbrab** [comment]
Nog enkele labels gezien die eindigen met een punt:
  Norm van het lijnvormig element.
  Supplementen van de verharding.
Suggestie voor urifragmenten niet toegepast (misschien met reden...) voor:
  Klasse Plankenbetuining gerecycleerd
  Klasse Plankenbetuining hout

**Comment by deefbas** [comment]
Deze euveltjes nog opgelost. Merci.
