### ISSUE TITLE
VOC installatie - detaillijst suggesties benamingen labels, UML namen en daaruit uri's

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-wegenenverkeer#55]
Klasse **Groep dwarse- en figuratiemarkering.**
Klasse **Groepering alle soorten markering.**
suggestie: punt verwijderen uit label

Klasse **Rioleringsgroepering**
uri fragment is #Riolering (zonder groepering)
suggestie: label "Riolering" of uri #Rioleringsgroepering

Eigenschap **positieTovRijweg**
suggestie: label aanpassen naar "positie ten opzichte van rijweg"

**Comment by deefbas** [comment]
Bonvenstaande issues zijn aangepast, volgende pub aanwezig.
