### ISSUE TITLE
VOC proef en meting - detaillijst suggesties benamingen labels, UML namen en daaruit uri's

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-wegenenverkeer#56]
Klasse **Proef a posteriori bitumineuze verharding.**
Klasse **Proef tijdens bestrating.**
Klasse **Proef tijdens bitumineuze verharding.**
suggestie: punt verwijderen uit label

**Comment by deefbas** [comment]
Punten zijn verwijderd. Volgende pub aanwezig.
