### ISSUE TITLE
VOC implementatieelement - detaillijst suggesties benamingen labels, UML namen en daaruit uri's

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-wegenenverkeer#57]
Klasse **Decimale graden**
Klasse **Euro**
Klasse **KubiekeMeter**
Klasse **Meter TAW**
suggestie: consequent alle klassen afgeleid van Kwantitatieve Waarde naam beginnen met "Kwantitatieve waarde in" en uri fragment beginnen met #KwantWrd zoals voor de meeste andere al gebeurd is

Klasse **uri**
suggestie: label aanpassen naar "URI"

**Comment by deefbas** [comment]
Aanpassingen doorgevoerd. Voor volgende pub.

**Comment by mvanbrab** [comment]
Bij nakijken hiervan op volgend fout label gestoten:
![afbeelding](https://user-images.githubusercontent.com/6448245/61050012-45c73700-a3e6-11e9-8d3c-4b40b9bb7e5d.png)

**Comment by deefbas** [comment]
Good catch, aangepast.
