### ISSUE TITLE
VOC levenscyclus - detaillijst suggesties benamingen labels, UML namen en daaruit uri's

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-wegenenverkeer#58]
Klasse **Beheer houtige vegetatie**
afwijkende uri vorm https://wegenenverkeer.data.vlaanderen.be/ns/levenscyclus#Beheer_houtigeVegetatie
suggestie: aanpassen naar https://wegenenverkeer.data.vlaanderen.be/ns/levenscyclus#BeheerHoutigeVegetatie

**Comment by deefbas** [comment]
Done. Volgende pub.
