### ISSUE TITLE
VOC implementatieelement - mappings naar http://www.w3.org/2001/XMLSchema#...

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-wegenenverkeer#59]
Ken aan de klassen die mappen op primitieve datatypes met uri's van de vorm http://www.w3.org/2001/XMLSchema#... een uri tag toe met met de betreffende waarde.
Zie ook https://github.com/Informatievlaanderen/OSLO-handleiding/blob/master/Modelleringsregels/OSLO-Modelleringsregels.pdf, 3.2.9 Datatypes.
Zie ook https://www.w3.org/TR/xmlschema-2/#namespaces.

Een overzicht van de gevonden datatypes (label) en de bijhorende uri's:
**Boolean** - http://www.w3.org/2001/XMLSchema#boolean
**Datum** - https://www.w3.org/2001/XMLSchema#date
**Datumtijd** - https://www.w3.org/2001/XMLSchema#datetime
**Decimaal getal** - http://www.w3.org/2001/XMLSchema#decimal
**Geheel getal** - http://www.w3.org/2001/XMLSchema#integer
**String** - http://www.w3.org/2001/XMLSchema#string
**Natuurlijk getal** - http://www.w3.org/2001/XMLSchema#nonNegativeInteger
uri (te wijzigen naar **URI**) - http://www.w3.org/2001/XMLSchema#anyURI

Merk op - in de definities wordt al naar die uri's verwezen (met https://, maar de correcte uri's zijn http://, beter ook corrigeren in de definities)

In https://github.com/Informatievlaanderen/OSLO-handleiding/blob/master/Modelleringsregels/OSLO-Modelleringsregels.pdf, 3.2.9 Datatypes wordt ook vermeld welke typenamen door de OSLO toolchain automatisch worden geconverteerd naar die uri's. Hiervoor moet dus in principe geen datatype expliciet gedefinieerd worden, maar het mag uiteraard wel. Zal dan in de spec verschijnen met zijn label, onder externe terminologie, met de uri in kwestie.

**Comment by deefbas** [comment]
Heb bij bovenvermelde primitieve datatypes de uri tag de voorgestelde waarde gegeven in het model.
Tevens de https omgevormd naar http.
