### ISSUE TITLE
VOC implementatieelement - eigenschappen zonder Bereik (Type verwijst naar niet gevonden datatype)

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-wegenenverkeer#60]
De eigenschap **mime-type** met uri https://wegenenverkeer.data.vlaanderen.be/ns/implementatieelement#AWVDocument.mimeType
heeft geen bereik (in UML wordt verwezen naar Type "AlgMimeType", maar komt nergens voor?)

Idem voor eigenschap **type** met uri https://wegenenverkeer.data.vlaanderen.be/ns/implementatieelement#SupplementenCBV.type (Type KleurSuppCBV?)

Idem voor eigenschap **kleur** met uri https://wegenenverkeer.data.vlaanderen.be/ns/implementatieelement#SupplementenCBV.kleur (Type TypeSuppCBV?)

Best eens algemene check doen naar ontbrekende verwezen types.

**Comment by deefbas** [comment]
Jordy heeft dit verder onderzocht en de issue gevonden :

////
Ik verzamel alle objecten in het diagram, en daarbij de bijbehorende classifier, in dit geval het datatype.
Echter, kan in dit datatype weer een verwijzing zitten naar een andere class (zoals in dit geval) , en zover ‘graaft’ de tool niet.

Dat zal ik aanpassen aan de code.
///
