### ISSUE TITLE
VOC implementatieelement - datatype RAL-kleur heeft slechts één attribuut

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-wegenenverkeer#61]
Dit datatype heeft slechts één eigenschap, nl. "waarde", een string. Waarom niet ineens elk attribuut van dit type meteen wijzigen naar het type string zelf? De formaatrestrictie die ik in de definitie zie staan kan toegevoegd worden aan de ap-usageNote-nl tag van het betreffende attribuut.

**Comment by deefbas** [comment]
Klopt, zal dit bekijken. Dit is zo historisch gegroeid prior OSLO. Indien er formattering van de string nodig was, werd dit in een datatype gestopt met bv. waarde attribuut en on de notes werd het formaat of de restrictie van de waarde genoteerd. 
Ik vermoed dat er meerdere datatypes zullen zijn die last hebben van dezelfde prior OSLO afspraak :-).

**Comment by deefbas** [comment]
Bij nader inzien, willen we dit toch zo behouden om volgende redenen : 
-Indien er nu een attribuut wordt getypeerd als RAL-kleur, kunnen we nu gewoon het datatype RAL-Kleur toekennen. Dit is in EA een manueel makkelijker proces in vergelijking met een string toe te kennen en de ap-usageNote-nl tag invullen met de constraint. Ook zal dit laatste vlugger tot 'foutjes' leiden door niet/vegeten invullen van deze tag.
-Indien in de toekomst wordt beslist om de constraint/formaatrestrictie/... te wijzigen, kan dat nu op 1 plaats, nl in het custom datatype zelf en niet op x-tal plaatsen waar deze ap-usageNote-nl van toepassing is.

**Comment by mvanbrab** [comment]
Ik ga deze dan sluiten met extra label "wontfix".
