### ISSUE TITLE
VOC implementatieelement - zin van de eigenschap 'uri type' in AWV object

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-wegenenverkeer#63]
Elk AWV object zou dus in dit attribuut de uri van het type van de afgeleide klasse bevatten.
Maar dat is redundant, want in een RDF dump wordt voor elk object een triple gegeneerd dat het type van het betreffende object vermeldt.

**Comment by deefbas** [comment]
Heb dit even besproken met Raf.  We hebben toch deze attribuut nodig, oa voor het volgende :

als een applicatie bv. geen rdf/json-ld ondersteunt, heb je het type van het betreffende object niet, dan heb je dit type-uri attribuut dus nodig om data te kunnen wisselen.

**Comment by mvanbrab** [comment]
OK, sluiten met deze verduidelijking.
