### ISSUE TITLE
IM algemeen - multiplicity n --> *

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-wegenenverkeer#64]
Multiplicity aanduiding "n" vervangen door "*" in de modellen. Zie ook https://www.omg.org/spec/UML/2.5.1/PDF 

Voorbeeld verkeerde output als gevolg in IM grondwerken:
![afbeelding](https://user-images.githubusercontent.com/6448245/60662795-a8a45580-9e5d-11e9-9e3c-26c6ad298542.png)

**Comment by deefbas** [comment]
Is aangepast naar 1..* voor volgende publicatie.
