### ISSUE TITLE
IM algemeen - wat is de bedoeling van de detailfiguren in sommige implementatiemodellen?

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-wegenenverkeer#67]
Wat is de bedoeling van de detailfiguren in de implementatiemodelspecificaties?
Ze kunnen toolchaingewijs niets bijdragen aan de specificatie, want een implementatiemodel wordt opgebouwd door het lezen van één figuur in een EAP bestand.

Klaarblijkelijk bevatten ze (een subset van) elementen op de hoofdfiguur (overview.jpg), maar dan anders geschikt.
Mij brengen ze vooral in de war. Als het de bedoeling is om in te zoomen, dan klik ik liever op de hoofdfiguur zodat ze in een apart browser window verschijnt, waarna ik zelf inzoom waar gewenst.

**Comment by deefbas** [comment]
Dit is, zoals we besproken hebben tijdens onze laatste call, niets meer dan een stuk uit het hoofddiagram. De eigenlijke ontwikkeling is gebeurd in deze kleinere aparte sub-diagrammen, daarna zijn deze samengevoegd en herschikt om zo compact en netjes mogelijk het hoofddiagram te kunnen publiceren. Ik bekijk of we de sub-diagrammen in dezelfde schikking als het hoofddiagram kunnen maken.

**Comment by mvanbrab** [comment]
In onze call suggereerde ik ook om de tekst "Detail figuren" (bijvoorbeeld hier voor Riolering)
![afbeelding](https://user-images.githubusercontent.com/6448245/61031209-50220a80-a3bf-11e9-86a7-233487d0b6ca.png)
aan te passen zodat deze stelt dat er in de detail figuren geen extra informatie vervat is ten opzichte van het diagram erboven. Dat alleen al zou mogelijke verwarring wegwerken. Ik neem aan dat dat veel minder werk is dan de diagrammen te herschikken,

Suggestie aanpassing: van "Detail figuren" naar "Extra figuren met gerichte selectie uit bovenstaande figuur (zelfde informatie)"

**Comment by deefbas** [comment]
Ok, klopt, de templates zijn aangepast naar suggestie.
