### ISSUE TITLE
IM union-datatypes - kardinaliteiten

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLOthema-wegenenverkeer#72]
Een voorbeeld uit union-datatypes:

![afbeelding](https://user-images.githubusercontent.com/6448245/60714477-72c5a680-9f1b-11e9-8715-deb6c7e3bd83.png)

Zoals de union datatypes nu gedefinieerd worden, zouden op de afzonderlijke attributen telkens kardinaliteiten [0..1] moeten staan, met een ap-usageNote-nl erbij op het union type zelf, die zegt dat slechts één van de attributen in praktijk kan aanwezig zijn.

**Comment by deefbas** [comment]
Heb dit via scripting aangepast. Nieuwe publicatie ronde loopt momenteel, niet zeker of dit reeds in de volgende versie V23 is te zien, zeker de versie daarop.
