### ISSUE TITLE
vocabularia-referenties in de implemenatiemodellen aanpassen

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLOthema-wegenenverkeer#73]
In de templates wordt verwezen naar het verkeerde domein: het moet subdomein wegenenverkeer.data.vlaanderen.be zijn

Zie bv. 
https://wegenenverkeer-test.data.vlaanderen.be/doc/implementatiemodel/grondwerken/ontwerpdocument/v21

**Comment by mvanbrab** [comment]
Zie ook #51 ; werd opgelost in v22.
