### ISSUE TITLE
verwijzingen naar extra documenten

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLOthema-wegenenverkeer#77]
Als je in de documenten wil verwijzen naar extra documenten zoals bijkomende figuren dan moet je het pad als volgt definiëren:

``` 
{% block images %}
   Detail figuren:
   <ul>
     <li><a href="{{ documentroot }}/html/Riolering_Put.pdf">Detail Put</a></li>
     <li><a href="{{ documentroot }}/html/Riolering_Buizen_LinkendeElementen.pdf">Linkende elementen</a></li>
 </ul>
{% endblock %}
```

voorbeeld zie riolering-ap.j2 geeft:
https://wegenenverkeer.data.vlaanderen.be/doc/implementatiemodel/riolering/ontwerpdocument/v22/

Dat zou nog enige deadlinks moeten oplossen.
Na de aanpassing een volledige generatie van alle documenten doen.

mvg,

Bert

**Comment by deefbas** [comment]
Heb ik blijkbaar op 'ready for closing' geplaatst zonder comment toe te voegen....
Ik heb dit toegepast en de deadlinks zijn hierdoor opgelost. Bedankt.
