### ISSUE TITLE
afwezig zijn van definities

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLOthema-wegenenverkeer#85]
in https://wegenenverkeer.data.vlaanderen.be/doc/implementatiemodel/riolering/
zijn er geen definities voor relatie `bevestigd`: zie bv. klasse https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#Bouwput

Dat komt omdat in de EAP geen enkele informatie aanwezig is om dit af te leiden. In het EAP model is er geen informatie in de tags voorzien, noch is er een link naar het vocabularium element aanwezig zodanig dat we de info hiervan zouden kunnen afleiden. 
`bevestigd` is gedefinieerd als een losgekoppelde, verse relatie.

Oplossing:
de noodzakelijke informatie overnemen in de tags.

**Comment by deefbas** [comment]
Jep, gecodeerd en dit werkt nu.

Bedankt
